# Generated by Django 3.2.7 on 2021-10-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='totalPrice',
        ),
    ]
